name: Deploy latest Docker image

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run tests
        run: go test ./...

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t jwtly10/googl-bye:latest .
          docker push jwtly10/googl-bye:latest

      - name: Deploy latest Docker image
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: googl-bye
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
